# Generated by Django 5.0.4 on 2024-04-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_rename_contact2_supplier_role_remove_supplier_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='role',
        ),
    ]
