# Generated by Django 5.0.4 on 2024-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0003_remove_supplier_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
