# Generated by Django 5.0.4 on 2024-04-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0004_supplier_contact2_supplier_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
    ]
