# Generated by Django 5.0.4 on 2024-04-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0005_alter_supplier_options_remove_supplier_contact2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
