# Generated by Django 5.0.4 on 2024-04-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0007_alter_item_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='suppliyer',
            new_name='supplier',
        ),
    ]
