# Generated by Django 5.0.4 on 2024-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0008_rename_suppliyer_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['ordered_at']},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
