# Generated by Django 5.0.4 on 2024-05-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0010_rename_stock_stock_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_in',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_out',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
