# Generated by Django 5.0.4 on 2024-05-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0011_stock_in_total_stock_out_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact1',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
