# Generated by Django 5.0.4 on 2024-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0012_alter_supplier_contact1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact1',
            field=models.CharField(max_length=255),
        ),
    ]
