# Generated by Django 5.0.4 on 2024-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0014_alter_stock_in_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_in',
            name='status',
            field=models.TextField(max_length=255),
        ),
    ]
