# Generated by Django 5.0.4 on 2024-05-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0016_alter_stock_in_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_out',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockout', to='stock_management.supplier'),
        ),
    ]
