# Generated by Django 5.0.4 on 2024-05-06 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0017_alter_stock_out_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_out',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stockout', to='stock_management.supplier'),
            preserve_default=False,
        ),
    ]
