# Generated by Django 5.0.4 on 2024-05-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0018_alter_stock_out_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock_out',
            options={'ordering': ['stocked_at']},
        ),
    ]
