# Generated by Django 5.0.4 on 2024-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(choices=[(1, 'Master'), (2, 'Dean of Study'), (3, 'Store keeper'), (4, 'Librarian'), (5, 'Hardware Manager'), (6, 'Teacher'), (7, 'Student')], default=7),
        ),
    ]
