# Generated by Django 5.0.4 on 2024-06-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_author_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['created']},
        ),
    ]
