# Generated by Django 5.0.4 on 2024-06-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='created',
        ),
    ]
