# Generated by Django 5.0.4 on 2024-06-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0005_alter_author_options_author_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='created',
        ),
    ]
