# Generated by Django 5.0.4 on 2024-06-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0006_alter_author_options_remove_author_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='eeee',
        ),
    ]
