# Generated by Django 5.0.4 on 2024-06-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0007_rename_name_author_eeee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='eeee',
            new_name='name',
        ),
    ]
